[package]
name = "lobster"
version = "0.7.0"
authors = ["Michele Lacchia <michelelacchia@gmail.com>"]
edition = "2018"
license = "ISC"

readme = "README.md"
description = "A fast limit order book (LOB)"
documentation = "https://docs.rs/lobster"
homepage = "https://github.com/rubik/lobster"
repository = "https://github.com/rubik/lobster"
keywords = ["orderbook", "order", "limit", "hft"]

[badges]
coveralls = { repository = "rubik/lobster" }
travis-ci = { repository = "rubik/lobster" }

[lib]
name = "lobster"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.16.4", features = ["extension-module"] }

[dev-dependencies]
criterion = "0.3"
csv = "1.1"
serde = { version = "1", features = ["derive"] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
incremental = false
overflow-checks = false
rpath = false
lto = "thin"
panic = "abort"
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
incremental = false
overflow-checks = false
rpath = false
lto = "thin"
codegen-units = 1

[[bench]]
name = "simple"
harness = false

[[bench]]
name = "quantcup"
harness = false
